# java -jar target/yolo-0.0.1-SNAPSHOT.jar

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_yolo
    username: root
    password: ""
    # driver-class-name: com.mysql.jdbc.Driver
    # todos:
    # topics:
    #   url: jdbc:mysql://localhost:3306/db_yolo
    #   username: root
    #   password: 123@abc
    #   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 30
          lob:
            non_contextual_creation: true

server:
  port: 8084
  servlet:
    context-path: /yolo
