spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yolo
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8084
